# Generated by Django 5.0.1 on 2024-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=15)),
                ('doj', models.DateField()),
            ],
        ),
    ]
