# Generated by Django 5.0.1 on 2024-01-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_acc_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='password',
            field=models.CharField(default=1234, max_length=40),
            preserve_default=False,
        ),
    ]
