# Generated by Django 5.0.1 on 2024-01-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_acc_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='usr',
        ),
    ]
