# Generated by Django 5.0.1 on 2024-01-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_acc_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
