# Generated by Django 5.0.1 on 2024-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_acc_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='id',
        ),
        migrations.AlterField(
            model_name='acc',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
